# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a59f2e302d9d7b50560c58f2d9699b236c00116c622a6689ca6b61a427633b2dd5aea02d84e2e0404c70d9e2f524d828ed02fb3d8b6bb6a3066ed923f4963c6e

test:
  secret_key_base: 16d7b8e3e043ec5621d4dac16eb86b745ce78018871f0ce6b0143461978ae8cec7987dc557ee4241b1efa4c638759721966f1df76e3a8ec6128e74fd469a7e0c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
